# Base image
FROM python:3.10-slim

# Set work directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y build-essential libpq-dev curl && rm -rf /var/lib/apt/lists/*

# Copy dependency files first (for layer caching)
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# copy required modules
COPY fastapi_app .
COPY pytest.ini .
COPY common /app/common
COPY datacreator /app/datacreator
COPY tests /app/tests

# Expose FastAPI port
EXPOSE 8000

# Start FastAPI app using uvicorn
CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "app:app", "--bind", "0.0.0.0:8000", "--workers", "1", "--timeout", "60"]
